# Generated by Django 2.2.12 on 2023-09-21 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_diary1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('diary_updated_date', models.DateField(auto_now=True)),
                ('diary_title', models.CharField(max_length=200)),
                ('diary_contents', models.TextField()),
            ],
        ),
    ]
